### ISSUE TITLE
Ability to flush logs or disable buffer for tests

### ISSUE THREAD

**Issue by ascandella** [axiomhq/next-axiom#68]
In `logger.ts`, all `log.<level>` calls pass through `throttledSendLogs`:https://github.com/axiomhq/next-axiom/blob/d8e0e7ca21ffa010621d1004eb380efb1d5bbab9/src/logger.ts#L45
which batches up calls to flush logs every 1 second.

When unit testing an application that has calls using the axiom logger, this leads to failures in e.g. `jest` because the calls to `console.log` (no environment variables specified) happen after the tests have finished:

```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "info - My log message here".

      at console.log (node_modules/.pnpm/@jest+console@29.0.3/node_modules/@jest/console/build/CustomConsole.js:172:10)
      at prettyPrint (node_modules/.pnpm/next-axiom@0.14.0_next@12.2.5/node_modules/next-axiom/src/logger.ts:200:15)
      at node_modules/.pnpm/next-axiom@0.14.0_next@12.2.5/node_modules/next-axiom/src/logger.ts:115:38
```

I'm interested in a way to either:

- Manually flush the buffer in an `afterAll()` hook
- Disable buffering entirely (via environment variables or otherwise)

So that I can use this logger without having to `sleep(1000)` in all my tests.

Looking at the source code I didn't see any obvious way to accomplish this without adding some new code. Do you all have thoughts on a preferred method to make this work?

**Comment by ascandella** [comment]
Ah of course, thanks!
